name = "math-playground"
compatibility_date = "2024-06-04"
send_metrics = false
account_id = "10393c29ef6e10da4ef439cd32928a94"
 
[[ d1_databases ]]
binding = "DB"
database_name = "production"
database_id = "4b816e36-1c7a-45b5-8696-5fa0846eb7a2"

[env.preview]
name = "math-playground"
workers_dev = true
 
[env.production]
name = "math-playground"
route = "math-playground.pages.dev/*"
workers_dev = false
