name = "math-playground"
compatibility_date = "2024-06-04"
send_metrics = false
node_compat = true
main = "src/worker.ts"
account_id = "10393c29ef6e10da4ef439cd32928a94"

[[d1_databases]]
binding = "DB"
database_name = "production"
database_id = "4b816e36-1c7a-45b5-8696-5fa0846eb7a2"
migrations_dir = "migrations"

# The necessary secrets are:
# - APP_URL - for preventing CORS errors
# - JWT_VERIFICATION_KEY - for Supabase @link https://supabase.com
#
# For local development, you can create a file called .dev.vars and use dotenv syntax.
#
# For deployed environments, you can use wrangler secrets to set these values.
# For example:
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
# Or use the Cloudflare web interface.
# @link https://developers.cloudflare.com/workers/platform/environment-variables/#environment-variables-via-the-dashboard
#
