name = "math-playground"
compatibility_date = "2024-06-04"
send_metrics = false
node_compat = true
route = "math-playground.pages.dev/*"
workers_dev = false

[env.preview]
name = "math-playground-preview"
workers_dev = true
